version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - go-webserver

  go-webserver:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - "8080:8080"