apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
      - name: go-container
        image: YOUR_DOCKER_REGISTRY/go-webserver:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP